## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "ITRS - 附中工研"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "工研社成立於1977年，是台灣最早的創客空間之一。在這裡，我們探索工業技術的無限可能。"
  logo = "images/banner.jpg"
  favicon = true

[Params.gtag]
  id = "AW-16678989424"
  label = "XWzhCMrYgc4ZEPDclJE-"

[Params.social]
  instagram = "https://www.instagram.com/hsnu_itrs/"
  discord = "https://discord.com/invite/fwSwZtFgzH"
  facebook = "https://www.facebook.com/HSNU.ITRS.infinite"
  github = "https://github.com/itrstw/"
  linktree = "https://linktr.ee/hsnu_itrs"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]